service: saaghibot

provider:
  name: aws
  region: eu-central-1
  runtime: nodejs10.x
  memorySize: 128
  environment:
    SAAGHIBOT_TOKEN: ${ssm:/saaghibot_token}

functions:
  saaghia:
    handler: handler.saaghia
    events:
      - http:
          path: saaghia
          method: post
          cors: true
      - schedule: rate(5 minutes)
